name: google_maps
author: "Alexandre Ardhuin <alexandre.ardhuin@gmail.com>"
homepage: https://github.com/a14n/dart-google-maps
version: 1.1.3
description: With that package you will be able to use Google Maps JavaScript API from Dart scripts.
dependencies:
  js: '>=0.0.15 <1.0.0'
#  js:
#    git: https://github.com/dart-lang/js-interop.git
  unittest: any
  meta: any
  browser: any

